# Generated by Django 6.0.6 on 2026-06-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIGCWEBS', '0004_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
