# Generated by Django 6.0.6 on 2026-06-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIGCWEBS', '0006_remove_gallery_image_remove_gallery_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
